name: Enforce Branch Naming

on:
  pull_request:

jobs:
  validate-branch-name:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch name
        run: |
          BRANCH_NAME="${{ github.head_ref }}"
          echo "Validating branch name: $BRANCH_NAME"
          if [[ ! "$BRANCH_NAME" =~ ^(feature|bugfix|hotfix)/[a-z0-9._-]+$ ]]; then
            echo "❌ Branch name '$BRANCH_NAME' does not follow naming convention."
            exit 1
          fi
          echo "✅ Branch name is valid."
